[project]
name = "msdagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain",
    "langchain-milvus",
    "langchain_ollama",
    "langchain_community",
    "langchain_text_splitters",
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "lxml",
    "pydantic",
    "pymilvus==2.5.10",
    "pyyaml",
    "sentence_transformers"
]
